spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/gilsinsa
    username: root
    password: 1111

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true